/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

int Collition_Fcn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Collition_Fcn_alloc_mem(void);
int Collition_Fcn_init_mem(int mem);
void Collition_Fcn_free_mem(int mem);
int Collition_Fcn_checkout(void);
void Collition_Fcn_release(int mem);
void Collition_Fcn_incref(void);
void Collition_Fcn_decref(void);
casadi_int Collition_Fcn_n_in(void);
casadi_int Collition_Fcn_n_out(void);
casadi_real Collition_Fcn_default_in(casadi_int i);
const char* Collition_Fcn_name_in(casadi_int i);
const char* Collition_Fcn_name_out(casadi_int i);
const casadi_int* Collition_Fcn_sparsity_in(casadi_int i);
const casadi_int* Collition_Fcn_sparsity_out(casadi_int i);
int Collition_Fcn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define Collition_Fcn_SZ_ARG 23
#define Collition_Fcn_SZ_RES 15
#define Collition_Fcn_SZ_IW 10
#define Collition_Fcn_SZ_W 100
#ifdef __cplusplus
} /* extern "C" */
#endif
