/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Collition_Detector_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif
#include <stdarg.h>
#include <stdio.h>

#ifndef casadi_real
#define casadi_real real_T
#endif

#ifndef casadi_int
#define casadi_int int_T
#endif

/* Add prefix to internal symbols */
#define casadi_axpy CASADI_PREFIX(axpy)
#define casadi_bilin CASADI_PREFIX(bilin)
#define casadi_casadi_qrqp_du_direction CASADI_PREFIX(casadi_qrqp_du_direction)
#define casadi_casadi_qrqp_pr_direction CASADI_PREFIX(casadi_qrqp_pr_direction)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mv CASADI_PREFIX(mv)
#define casadi_qp_data CASADI_PREFIX(qp_data)
#define casadi_qp_init CASADI_PREFIX(qp_init)
#define casadi_qp_prob CASADI_PREFIX(qp_prob)
#define casadi_qp_setup CASADI_PREFIX(qp_setup)
#define casadi_qp_work CASADI_PREFIX(qp_work)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_qrqp_calc_dependent CASADI_PREFIX(qrqp_calc_dependent)
#define casadi_qrqp_calc_sens CASADI_PREFIX(qrqp_calc_sens)
#define casadi_qrqp_calc_step CASADI_PREFIX(qrqp_calc_step)
#define casadi_qrqp_data CASADI_PREFIX(qrqp_data)
#define casadi_qrqp_du CASADI_PREFIX(qrqp_du)
#define casadi_qrqp_du_check CASADI_PREFIX(qrqp_du_check)
#define casadi_qrqp_du_index CASADI_PREFIX(qrqp_du_index)
#define casadi_qrqp_dual_blocking CASADI_PREFIX(qrqp_dual_blocking)
#define casadi_qrqp_dual_breakpoints CASADI_PREFIX(qrqp_dual_breakpoints)
#define casadi_qrqp_enforceable CASADI_PREFIX(qrqp_enforceable)
#define casadi_qrqp_expand_step CASADI_PREFIX(qrqp_expand_step)
#define casadi_qrqp_factorize CASADI_PREFIX(qrqp_factorize)
#define casadi_qrqp_flag_t CASADI_PREFIX(qrqp_flag_t)
#define casadi_qrqp_flip CASADI_PREFIX(qrqp_flip)
#define casadi_qrqp_flip_check CASADI_PREFIX(qrqp_flip_check)
#define casadi_qrqp_init CASADI_PREFIX(qrqp_init)
#define casadi_qrqp_iterate CASADI_PREFIX(qrqp_iterate)
#define casadi_qrqp_kkt CASADI_PREFIX(qrqp_kkt)
#define casadi_qrqp_kkt_dot CASADI_PREFIX(qrqp_kkt_dot)
#define casadi_qrqp_kkt_residual CASADI_PREFIX(qrqp_kkt_residual)
#define casadi_qrqp_kkt_vector CASADI_PREFIX(qrqp_kkt_vector)
#define casadi_qrqp_linesearch CASADI_PREFIX(qrqp_linesearch)
#define casadi_qrqp_pr CASADI_PREFIX(qrqp_pr)
#define casadi_qrqp_pr_index CASADI_PREFIX(qrqp_pr_index)
#define casadi_qrqp_prepare CASADI_PREFIX(qrqp_prepare)
#define casadi_qrqp_primal_blocking CASADI_PREFIX(qrqp_primal_blocking)
#define casadi_qrqp_print_colcomb CASADI_PREFIX(qrqp_print_colcomb)
#define casadi_qrqp_print_header CASADI_PREFIX(qrqp_print_header)
#define casadi_qrqp_print_iteration CASADI_PREFIX(qrqp_print_iteration)
#define casadi_qrqp_prob CASADI_PREFIX(qrqp_prob)
#define casadi_qrqp_reset CASADI_PREFIX(qrqp_reset)
#define casadi_qrqp_setup CASADI_PREFIX(qrqp_setup)
#define casadi_qrqp_singular_step CASADI_PREFIX(qrqp_singular_step)
#define casadi_qrqp_take_step CASADI_PREFIX(qrqp_take_step)
#define casadi_qrqp_work CASADI_PREFIX(qrqp_work)
#define casadi_qrqp_zero_blocking CASADI_PREFIX(qrqp_zero_blocking)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_to_mex CASADI_PREFIX(to_mex)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

struct casadi_qp_prob {
  const casadi_int *sp_a, *sp_h;
  casadi_int nx, na, nz;
  casadi_int nnz_a, nnz_h;
};
void casadi_qp_setup(struct casadi_qp_prob* p) {
  p->na = p->sp_a[0];
  p->nx = p->sp_a[1];
  p->nz = p->na+p->nx;
  p->nnz_a = p->sp_a[2+p->sp_a[1]];
  p->nnz_h = p->sp_h[2+p->sp_h[1]];
}
struct casadi_qp_data {
  const struct casadi_qp_prob* prob;
  int unified_return_status;
  int success;
  casadi_int iter_count;
  const casadi_real *a, *h, *g, *lbx, *ubx, *lba, *uba, *x0, *lam_x0, *lam_a0;
  casadi_real *f, *x, *lam_x, *lam_a;
};
void casadi_qp_init(struct casadi_qp_data* d, casadi_int** iw, casadi_real** w) {
}
void casadi_qp_work(const struct casadi_qp_prob* p, casadi_int* sz_arg, casadi_int* sz_res,
    casadi_int* sz_iw, casadi_int* sz_w) {
  *sz_arg = *sz_res = 0;
  *sz_w = *sz_iw = 0;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

casadi_int casadi_max(casadi_int x, casadi_int y) {
  return x>y ? x : y;
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_axpy(casadi_int n, casadi_real alpha, const casadi_real* x, casadi_real* y) {
  casadi_int i;
  if (!x || !y) return;
  for (i=0; i<n; ++i) *y++ += alpha**x++;
}

void casadi_mv(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, casadi_real* z, casadi_int tr) {
  casadi_int ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!x || !y || !z) return;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el<colind_x[i+1]; ++el) {
        z[i] += x[el] * y[row_x[el]];
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el<colind_x[i+1]; ++el) {
        z[row_x[el]] += x[el] * y[i];
      }
    }
  }
}

casadi_real casadi_bilin(const casadi_real* A, const casadi_int* sp_A, const casadi_real* x, const casadi_real* y) {
  casadi_int ncol_A, cc, rr, el;
  const casadi_int *colind_A, *row_A;
  casadi_real ret;
  ncol_A = sp_A[1];
  colind_A = sp_A+2; row_A = sp_A + 2 + ncol_A+1;
  ret=0;
  for (cc=0; cc<ncol_A; ++cc) {
    for (el=colind_A[cc]; el<colind_A[cc+1]; ++el) {
      rr=row_A[el];
      ret += x[rr]*A[el]*y[cc];
    }
  }
  return ret;
}

#ifndef casadi_inf
  #define casadi_inf INFINITY
#endif

#ifndef casadi_real_min
  #define casadi_real_min 2.2251e-308
#endif

struct casadi_qrqp_prob {
  const struct casadi_qp_prob* qp;
  const casadi_int *sp_at, *sp_kkt;
  const casadi_int *prinv, *pc, *sp_v, *sp_r;
  casadi_real dmin;
  casadi_real inf;
  casadi_real min_lam;
  casadi_int max_iter;
  casadi_real constr_viol_tol, dual_inf_tol;
};
void casadi_qrqp_setup(struct casadi_qrqp_prob* p) {
  p->dmin = casadi_real_min;
  p->inf = casadi_inf;
  p->min_lam = 0;
  p->max_iter = 1000;
  p->constr_viol_tol = 1e-8;
  p->dual_inf_tol = 1e-8;
}
typedef enum {
  QP_SUCCESS,
  QP_MAX_ITER,
  QP_NO_SEARCH_DIR,
  QP_PRINTING_ERROR
} casadi_qrqp_flag_t;
struct casadi_qrqp_data {
  const struct casadi_qrqp_prob* prob;
  struct casadi_qp_data* qp;
  casadi_real f;
  casadi_qrqp_flag_t status;
  casadi_real *lbz, *ubz, *z, *infeas, *tinfeas, *sens, *lam, *w, *dz, *dlam;
  casadi_int *iw, *neverzero, *neverlower, *neverupper, *lincomb;
  casadi_real *nz_at, *nz_kkt, *beta, *nz_v, *nz_r;
  const char *msg;
  casadi_int msg_ind;
  casadi_real tau;
  casadi_int sing;
  int has_search_dir;
  casadi_real mina;
  casadi_int imina;
  casadi_real pr, du, epr, edu;
  casadi_int ipr, idu;
  casadi_int index, sign;
  casadi_int r_index, r_sign;
  casadi_int iter;
};
void casadi_qrqp_work(const struct casadi_qrqp_prob* p, casadi_int* sz_arg, casadi_int* sz_res,
    casadi_int* sz_iw, casadi_int* sz_w) {
  casadi_int nnz_a, nnz_kkt, nnz_v, nnz_r;
  casadi_qp_work(p->qp, sz_arg, sz_res, sz_iw, sz_w);
  nnz_a = p->qp->sp_a[2+p->qp->sp_a[1]];
  nnz_kkt = p->sp_kkt[2+p->sp_kkt[1]];
  nnz_v = p->sp_v[2+p->sp_v[1]];
  nnz_r = p->sp_r[2+p->sp_r[1]];
  *sz_w = casadi_max(*sz_w, p->qp->nz);
  *sz_iw = casadi_max(*sz_iw, p->qp->nz);
  *sz_w = casadi_max(*sz_w, 2*p->qp->nz);
  *sz_w += nnz_kkt;
  *sz_w += p->qp->nz;
  *sz_w += p->qp->nz;
  *sz_w += p->qp->nz;
  *sz_w += p->qp->nz;
  *sz_w += p->qp->nz;
  *sz_w += p->qp->nz;
  *sz_w += casadi_max(nnz_v+nnz_r, nnz_kkt);
  *sz_w += p->qp->nz;
  *sz_w += nnz_a;
  *sz_w += p->qp->nx;
  *sz_w += p->qp->nx;
  *sz_w += p->qp->nz;
  *sz_iw += p->qp->nz;
  *sz_iw += p->qp->nz;
  *sz_iw += p->qp->nz;
  *sz_iw += p->qp->nz;
}
void casadi_qrqp_init(struct casadi_qrqp_data* d, casadi_int** iw, casadi_real** w) {
  casadi_int nnz_a, nnz_kkt, nnz_v, nnz_r;
  const struct casadi_qrqp_prob* p = d->prob;
  nnz_a = p->qp->sp_a[2+p->qp->sp_a[1]];
  nnz_kkt = p->sp_kkt[2+p->sp_kkt[1]];
  nnz_v = p->sp_v[2+p->sp_v[1]];
  nnz_r = p->sp_r[2+p->sp_r[1]];
  d->nz_kkt = *w; *w += nnz_kkt;
  d->z = *w; *w += p->qp->nz;
  d->lbz = *w; *w += p->qp->nz;
  d->ubz = *w; *w += p->qp->nz;
  d->lam = *w; *w += p->qp->nz;
  d->dz = *w; *w += p->qp->nz;
  d->dlam = *w; *w += p->qp->nz;
  d->nz_v = *w; *w += casadi_max(nnz_v+nnz_r, nnz_kkt);
  d->beta = *w; *w += p->qp->nz;
  d->nz_at = *w; *w += nnz_a;
  d->infeas = *w; *w += p->qp->nx;
  d->tinfeas = *w; *w += p->qp->nx;
  d->sens = *w; *w += p->qp->nz;
  d->neverzero = *iw; *iw += p->qp->nz;
  d->neverupper = *iw; *iw += p->qp->nz;
  d->neverlower = *iw; *iw += p->qp->nz;
  d->lincomb = *iw; *iw += p->qp->nz;
  d->w = *w;
  d->iw = *iw;
  d->nz_r = d->nz_v + nnz_v;
}
int casadi_qrqp_reset(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  d->msg = 0;
  d->tau = 0.;
  d->sing = 0;
  for (i=0; i<p->qp->nz; ++i) {
    d->neverzero[i] = d->lbz[i] == d->ubz[i];
    d->neverupper[i] = d->ubz[i] == p->inf;
    d->neverlower[i] = d->lbz[i] == -p->inf;
    if (d->neverzero[i] && d->neverupper[i] && d->neverlower[i]) return 1;
    if (!d->neverzero[i] && fabs(d->lam[i]) < p->min_lam) d->lam[i] = 0.;
    if (d->neverzero[i] && d->lam[i] == 0.) {
      d->lam[i] = d->neverupper[i]
                || d->z[i]-d->lbz[i] <= d->ubz[i]-d->z[i] ? -p->dmin : p->dmin;
    } else if (d->neverupper[i] && d->lam[i]>0.) {
      d->lam[i] = d->neverzero[i] ? -p->dmin : 0.;
    } else if (d->neverlower[i] && d->lam[i]<0.) {
      d->lam[i] = d->neverzero[i] ? p->dmin : 0.;
    }
  }
  casadi_trans(d->qp->a, p->qp->sp_a, d->nz_at, p->sp_at, d->iw);
  d->index = -2;
  d->sign = 0;
  d->r_index = -2;
  d->r_sign = 0;
  d->iter = 0;
  return 0;
}
void casadi_qrqp_pr(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  d->pr = 0;
  d->ipr = -1;
  for (i=0; i<p->qp->nz; ++i) {
    if (d->z[i] > d->ubz[i]+d->pr) {
      d->pr = d->z[i]-d->ubz[i];
      d->ipr = i;
    } else if (d->z[i] < d->lbz[i]-d->pr) {
      d->pr = d->lbz[i]-d->z[i];
      d->ipr = i;
    }
  }
}
void casadi_qrqp_du(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  d->du = 0;
  d->idu = -1;
  for (i=0; i<p->qp->nx; ++i) {
    if (d->infeas[i] > d->du) {
      d->du = d->infeas[i];
      d->idu = i;
    } else if (d->infeas[i] < -d->du) {
      d->du = -d->infeas[i];
      d->idu = i;
    }
  }
}
int casadi_qrqp_du_check(struct casadi_qrqp_data* d, casadi_int i) {
  casadi_int k;
  casadi_real new_du;
  const casadi_int *at_colind, *at_row;
  const struct casadi_qrqp_prob* p = d->prob;
  at_colind = p->sp_at + 2;
  at_row = at_colind + p->qp->na + 1;
  if (i<p->qp->nx) {
    new_du = fabs(d->infeas[i]-d->lam[i]);
  } else {
    new_du = 0.;
    for (k=at_colind[i-p->qp->nx]; k<at_colind[i-p->qp->nx+1]; ++k) {
      new_du = casadi_fmax(new_du, fabs(d->infeas[at_row[k]]-d->nz_at[k]*d->lam[i]));
    }
  }
  return new_du <= d->du;
}
void casadi_qrqp_du_index(struct casadi_qrqp_data* d) {
  casadi_int i, s;
  casadi_real best_sens;
  const struct casadi_qrqp_prob* p = d->prob;
  d->index = -1;
  best_sens = -1;
  for (i = 0; i < p->qp->nz; ++i) {
    if (d->sens[i] == 0.) continue;
    if (d->lam[i] == 0) {
      s = d->sens[i] > 0 ? 1 : -1;
      if (s > 0 ? d->neverupper[i] : d->neverlower[i]) continue;
    } else {
      s = 0;
      if (d->neverzero[i]) continue;
      if (d->lam[i] > 0. ? d->sens[i] > 0. : d->sens[i] < 0.) continue;
      if (!casadi_qrqp_du_check(d, i)) continue;
    }
    if (fabs(d->sens[i]) > best_sens) {
      best_sens = fabs(d->sens[i]);
      d->index = i;
      d->sign = s;
    }
  }
  if (d->index >= 0) {
    if (d->sign > 0) {
      d->msg = "Enforced ubz to reduce |du|";
    } else if (d->sign < 0) {
      d->msg = "Enforced lbz to reduce |du|";
    } else if (d->lam[d->index] > 0) {
      d->msg = "Dropped ubz to reduce |du|";
    } else {
      d->msg = "Dropped lbz to reduce |du|";
    }
    d->msg_ind = d->index;
  }
}
void casadi_qrqp_pr_index(struct casadi_qrqp_data* d) {
  if (d->lam[d->ipr] == 0.) {
    if (d->z[d->ipr] < d->lbz[d->ipr]) {
      d->sign = -1;
      d->msg = "Added lbz to reduce |pr|";
    } else {
      d->sign = 1;
      d->msg = "Added ubz to reduce |pr|";
    }
    d->msg_ind = d->ipr;
    d->index = d->ipr;
  } else {
    d->index = -1;
  }
}
void casadi_qrqp_kkt(struct casadi_qrqp_data* d) {
  casadi_int i, k;
  const casadi_int *h_colind, *h_row, *a_colind, *a_row, *at_colind, *at_row,
                   *kkt_colind, *kkt_row;
  const struct casadi_qrqp_prob* p = d->prob;
  a_row = (a_colind = p->qp->sp_a+2) + p->qp->nx + 1;
  at_row = (at_colind = p->sp_at+2) + p->qp->na + 1;
  h_row = (h_colind = p->qp->sp_h+2) + p->qp->nx + 1;
  kkt_row = (kkt_colind = p->sp_kkt+2) + p->qp->nz + 1;
  casadi_clear(d->w, p->qp->nz);
  for (i=0; i<p->qp->nz; ++i) {
    if (i<p->qp->nx) {
      if (d->lam[i]==0) {
        for (k=h_colind[i]; k<h_colind[i+1]; ++k) d->w[h_row[k]] = d->qp->h[k];
        for (k=a_colind[i]; k<a_colind[i+1]; ++k) d->w[p->qp->nx+a_row[k]] = d->qp->a[k];
      } else {
        d->w[i] = 1.;
      }
    } else {
      if (d->lam[i]==0) {
        d->w[i] = -1.;
      } else {
        for (k=at_colind[i-p->qp->nx]; k<at_colind[i-p->qp->nx+1]; ++k) {
          d->w[at_row[k]] = d->nz_at[k];
        }
      }
    }
    for (k=kkt_colind[i]; k<kkt_colind[i+1]; ++k) {
      d->nz_kkt[k] = d->w[kkt_row[k]];
      d->w[kkt_row[k]] = 0;
    }
  }
}
void casadi_qrqp_kkt_vector(struct casadi_qrqp_data* d, casadi_real* kkt_i, casadi_int i) {
  casadi_int k;
  const casadi_int *h_colind, *h_row, *a_colind, *a_row, *at_colind, *at_row;
  const struct casadi_qrqp_prob* p = d->prob;
  a_row = (a_colind = p->qp->sp_a+2) + p->qp->nx + 1;
  at_row = (at_colind = p->sp_at+2) + p->qp->na + 1;
  h_row = (h_colind = p->qp->sp_h+2) + p->qp->nx + 1;
  casadi_clear(kkt_i, p->qp->nz);
  if (i<p->qp->nx) {
    for (k=h_colind[i]; k<h_colind[i+1]; ++k) kkt_i[h_row[k]] = d->qp->h[k];
    for (k=a_colind[i]; k<a_colind[i+1]; ++k) kkt_i[p->qp->nx+a_row[k]] = d->qp->a[k];
  } else {
    for (k=at_colind[i-p->qp->nx]; k<at_colind[i-p->qp->nx+1]; ++k) {
      kkt_i[at_row[k]] = -d->nz_at[k];
    }
  }
  kkt_i[i] -= 1.;
}
casadi_real casadi_qrqp_kkt_dot(struct casadi_qrqp_data* d, const casadi_real* v, casadi_int i) {
  casadi_int k;
  const casadi_int *h_colind, *h_row, *a_colind, *a_row, *at_colind, *at_row;
  casadi_real r;
  const struct casadi_qrqp_prob* p = d->prob;
  a_row = (a_colind = p->qp->sp_a + 2) + p->qp->nx + 1;
  at_row = (at_colind = p->sp_at + 2) + p->qp->na + 1;
  h_row = (h_colind = p->qp->sp_h + 2) + p->qp->nx + 1;
  r = v[i];
  if (i < p->qp->nx) {
    for (k=h_colind[i]; k<h_colind[i+1]; ++k) r -= v[h_row[k]] * d->qp->h[k];
    for (k=a_colind[i]; k<a_colind[i+1]; ++k) r -= v[p->qp->nx+a_row[k]] * d->qp->a[k];
  } else {
    for (k=at_colind[i-p->qp->nx]; k<at_colind[i-p->qp->nx+1]; ++k) {
      r += v[at_row[k]] * d->nz_at[k];
    }
  }
  return r;
}
void casadi_qrqp_kkt_residual(struct casadi_qrqp_data* d, casadi_real* r) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  for (i=0; i<p->qp->nz; ++i) {
    if (d->lam[i]>0.) {
      r[i] = d->ubz[i]-d->z[i];
    } else if (d->lam[i]<0.) {
      r[i] = d->lbz[i]-d->z[i];
    } else if (i<p->qp->nx) {
      r[i] = d->lam[i]-d->infeas[i];
    } else {
      r[i] = d->lam[i];
    }
  }
}
int casadi_qrqp_zero_blocking(struct casadi_qrqp_data* d) {
  casadi_int i;
  casadi_real dz_max = 0;
  const struct casadi_qrqp_prob* p = d->prob;
  for (i = 0; i < p->qp->nz; ++i) {
    if (d->dz[i] < -dz_max && d->lbz[i] - d->z[i] >= d->epr) {
      dz_max = -d->dz[i];
      d->index = i;
      d->sign = -1;
      d->msg = "lbz violated with zero step";
      d->msg_ind = d->index;
    } else if (d->dz[i] > dz_max && d->z[i] - d->ubz[i] >= d->epr) {
      dz_max = d->dz[i];
      d->index = i;
      d->sign = 1;
      d->msg = "ubz violated with zero step";
      d->msg_ind = d->index;
    }
  }
  return dz_max > 0;
}
void casadi_qrqp_primal_blocking(struct casadi_qrqp_data* d) {
  casadi_int i;
  casadi_real trial_z;
  const struct casadi_qrqp_prob* p = d->prob;
  if (casadi_qrqp_zero_blocking(d)) {
    d->tau = 0.;
    return;
  }
  for (i = 0; i < p->qp->nz; ++i) {
    if (d->dz[i] == 0.) continue;
    trial_z = d->z[i] + d->tau * d->dz[i];
    if (d->dz[i] < 0 && trial_z < d->lbz[i] - d->epr) {
      d->tau = (d->lbz[i] - d->epr - d->z[i]) / d->dz[i];
      d->index = d->lam[i] < 0. ? -1 : i;
      d->sign = -1;
      d->msg = "Enforcing lbz";
      d->msg_ind = i;
    } else if (d->dz[i] > 0 && trial_z > d->ubz[i] + d->epr) {
      d->tau = (d->ubz[i] + d->epr - d->z[i]) / d->dz[i];
      d->index = d->lam[i] > 0. ? -1 : i;
      d->sign = 1;
      d->msg = "Enforcing ubz";
      d->msg_ind = i;
    }
    if (d->tau <= 0) return;
  }
}
casadi_int casadi_qrqp_dual_breakpoints(struct casadi_qrqp_data* d, casadi_real* tau_list,
                                      casadi_int* ind_list, casadi_real tau) {
  casadi_int i, n_tau, loc, next_ind, tmp_ind, j;
  casadi_real trial_lam, new_tau, next_tau, tmp_tau;
  const struct casadi_qrqp_prob* p = d->prob;
  tau_list[0] = tau;
  ind_list[0] = -1;
  n_tau = 1;
  for (i=0; i<p->qp->nz; ++i) {
    if (d->dlam[i]==0.) continue;
    if (d->lam[i]==0.) continue;
    trial_lam = d->lam[i] + tau*d->dlam[i];
    if (d->lam[i]>0 ? trial_lam>=0 : trial_lam<=0) continue;
    new_tau = -d->lam[i]/d->dlam[i];
    for (loc=0; loc<n_tau-1; ++loc) {
      if (new_tau<tau_list[loc]) break;
    }
    n_tau++;
    next_tau=new_tau;
    next_ind=i;
    for (j=loc; j<n_tau; ++j) {
      tmp_tau = tau_list[j];
      tau_list[j] = next_tau;
      next_tau = tmp_tau;
      tmp_ind = ind_list[j];
      ind_list[j] = next_ind;
      next_ind = tmp_ind;
    }
  }
  return n_tau;
}
casadi_int casadi_qrqp_dual_blocking(struct casadi_qrqp_data* d) {
  casadi_int i, n_tau, j, k, du_index;
  casadi_real tau_k, dtau, new_infeas, tau1, infeas, tinfeas;
  const casadi_int *at_colind, *at_row;
  const struct casadi_qrqp_prob* p = d->prob;
  at_row = (at_colind = p->sp_at+2) + p->qp->na + 1;
  n_tau = casadi_qrqp_dual_breakpoints(d, d->w, d->iw, d->tau);
  du_index = -1;
  tau_k = 0.;
  for (j=0; j<n_tau; ++j) {
    dtau = d->w[j] - tau_k;
    for (k=0; k<p->qp->nx; ++k) {
      infeas  = d->infeas[k];
      tinfeas  = d->tinfeas[k];
      if (fabs(tinfeas)<1e-14) {
        continue;
      } else if (tinfeas<0) {
        infeas *= -1;
        tinfeas *= -1;
      }
      new_infeas = infeas + dtau*tinfeas;
      if (new_infeas > d->edu) {
        tau1 = casadi_fmax(tau_k, tau_k + (d->edu - infeas)/tinfeas);
        if (tau1 < d->tau) {
          d->tau = tau1;
          du_index = k;
        }
      }
    }
    casadi_axpy(p->qp->nx, casadi_fmin(d->tau - tau_k, dtau), d->tinfeas, d->infeas);
    if (du_index>=0) return du_index;
    tau_k = d->w[j];
    i = d->iw[j];
    if (i<0) break;
    if (!d->neverzero[i]) {
      if (i<p->qp->nx) {
        d->tinfeas[i] -= d->dlam[i];
      } else {
        for (k=at_colind[i-p->qp->nx]; k<at_colind[i-p->qp->nx+1]; ++k) {
          d->tinfeas[at_row[k]] -= d->nz_at[k]*d->dlam[i];
        }
      }
    }
  }
  return du_index;
}
void casadi_qrqp_take_step(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  for (i=0; i<p->qp->nz; ++i) d->iw[i] = d->lam[i]>0. ? 1 : d->lam[i]<0 ? -1 : 0;
  casadi_axpy(p->qp->nz, d->tau, d->dz, d->z);
  casadi_axpy(p->qp->nz, d->tau, d->dlam, d->lam);
  for (i=0; i<p->qp->nz; ++i) {
    if (d->neverzero[i] && (d->iw[i]<0 ? d->lam[i]>0 : d->lam[i]<0)) {
      d->iw[i]=-d->iw[i];
    }
    switch (d->iw[i]) {
      case -1: d->lam[i] = casadi_fmin(d->lam[i], -p->dmin); break;
      case  1: d->lam[i] = casadi_fmax(d->lam[i],  p->dmin); break;
      case  0: d->lam[i] = 0.; break;
    }
  }
}
int casadi_qrqp_flip_check(struct casadi_qrqp_data* d) {
  const struct casadi_qrqp_prob* p = d->prob;
  casadi_qrqp_kkt_vector(d, d->dlam, d->index);
  if (d->sign == 0) casadi_scal(p->qp->nz, -1., d->dlam);
  casadi_qr_solve(d->dlam, 1, 0, p->sp_v, d->nz_v, p->sp_r, d->nz_r, d->beta,
    p->prinv, p->pc, d->w);
  if (fabs(d->dlam[d->index]-1.) >= 1e-12) return 0;
  casadi_clear(d->dz, p->qp->nz);
  d->dz[d->index] = 1;
  casadi_qr_solve(d->dz, 1, 1, p->sp_v, d->nz_v, p->sp_r, d->nz_r, d->beta,
    p->prinv, p->pc, d->w);
  casadi_scal(p->qp->nz, 1./sqrt(casadi_dot(p->qp->nz, d->dlam, d->dlam)), d->dlam);
  casadi_scal(p->qp->nz, 1./sqrt(casadi_dot(p->qp->nz, d->dz, d->dz)), d->dz);
  return 1;
}
void casadi_qrqp_factorize(struct casadi_qrqp_data* d) {
  const struct casadi_qrqp_prob* p = d->prob;
  if (d->has_search_dir) {
    d->sing = 1;
    return;
  }
  casadi_qrqp_kkt(d);
  casadi_qr(p->sp_kkt, d->nz_kkt, d->w, p->sp_v, d->nz_v, p->sp_r,
            d->nz_r, d->beta, p->prinv, p->pc);
  d->sing = casadi_qr_singular(&d->mina, &d->imina, d->nz_r, p->sp_r, p->pc, 1e-12);
}
void casadi_qrqp_expand_step(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  casadi_clear(d->dlam, p->qp->nx);
  casadi_mv(d->qp->h, p->qp->sp_h, d->dz, d->dlam, 0);
  casadi_mv(d->qp->a, p->qp->sp_a, d->dz + p->qp->nx, d->dlam, 1);
  casadi_scal(p->qp->nx, -1., d->dlam);
  for (i = 0; i < p->qp->nx; ++i) if (d->lam[i] == 0.) d->dlam[i] = 0.;
  casadi_copy(d->dz+p->qp->nx, p->qp->na, d->dlam + p->qp->nx);
  casadi_clear(d->dz + p->qp->nx, p->qp->na);
  casadi_mv(d->qp->a, p->qp->sp_a, d->dz, d->dz + p->qp->nx, 0);
  for (i = 0; i < p->qp->nz; ++i) if (fabs(d->dz[i]) < 1e-14) d->dz[i] = 0.;
  casadi_clear(d->tinfeas, p->qp->nx);
  casadi_mv(d->qp->h, p->qp->sp_h, d->dz, d->tinfeas, 0);
  casadi_mv(d->qp->a, p->qp->sp_a, d->dlam + p->qp->nx, d->tinfeas, 1);
  casadi_axpy(p->qp->nx, 1., d->dlam, d->tinfeas);
}
int casadi_qrqp_pr_direction(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  for (i=0; i<p->qp->nz; ++i) {
    if (d->lbz[i] - d->z[i] >= d->epr) {
      if (d->dz[i] < 0 || d->dlam[i] > 0) return 1;
    } else if (d->z[i] - d->ubz[i] >= d->epr) {
      if (d->dz[i] > 0 || d->dlam[i] < 0) return 1;
    }
  }
  return 0;
}
int casadi_qrqp_du_direction(struct casadi_qrqp_data* d) {
  casadi_int i;
  const struct casadi_qrqp_prob* p = d->prob;
  for (i=0; i<p->qp->nx; ++i) {
    if (d->infeas[i] <= -d->edu && d->tinfeas[i] < -1e-12) {
      return 1;
    } else if (d->infeas[i] >= d->edu && d->tinfeas[i] > 1e-12) {
      return 1;
    }
  }
  return 0;
}
int casadi_qrqp_enforceable(struct casadi_qrqp_data* d, casadi_int i, casadi_int s) {
  casadi_int k;
  const casadi_int *at_colind, *at_row;
  const struct casadi_qrqp_prob* p = d->prob;
  if (fabs(d->infeas[i]) < d->edu) return 1;
  at_colind = p->sp_at + 2;
  at_row = at_colind + p->qp->na + 1;
  if (i<p->qp->nx) {
    return (s < 0) == (d->infeas[i] > 0);
  } else {
    for (k=at_colind[i-p->qp->nx]; k<at_colind[i-p->qp->nx+1]; ++k) {
      if (d->nz_at[k] > 0) {
        if ((s > 0) == (d->infeas[at_row[k]] > 0)) return 0;
      } else if (d->nz_at[k] < 0) {
        if ((s < 0) == (d->infeas[at_row[k]] > 0)) return 0;
      }
    }
    return 1;
  }
}
int casadi_qrqp_singular_step(struct casadi_qrqp_data* d) {
  casadi_real tau_test, tau;
  casadi_int nnz_kkt, nk, k, i, best_k, best_neg, neg;
  const struct casadi_qrqp_prob* p = d->prob;
  for (i = 0; i < p->qp->nz; ++i) d->lincomb[i] = 0;
  for (k = 0; k < d->sing; ++k) {
    if (!d->has_search_dir) {
      casadi_qr_colcomb(d->dlam, d->nz_r, p->sp_r, p->pc, 1e-12, k);
    }
    for (i = 0; i < p->qp->nz; ++i) if (fabs(d->dlam[i]) >= 1e-12) d->lincomb[i]++;
  }
  if (d->has_search_dir) {
    nk = 1;
  } else {
    casadi_trans(d->nz_kkt, p->sp_kkt, d->nz_v, p->sp_kkt, d->iw);
    nnz_kkt = p->sp_kkt[2+p->qp->nz];
    casadi_copy(d->nz_v, nnz_kkt, d->nz_kkt);
    casadi_qr(p->sp_kkt, d->nz_kkt, d->w, p->sp_v, d->nz_v, p->sp_r, d->nz_r,
              d->beta, p->prinv, p->pc);
    nk = casadi_qr_singular(0, 0, d->nz_r, p->sp_r, p->pc, 1e-12);
  }
  best_k = best_neg = -1;
  tau = p->inf;
  for (k=0; k<nk; ++k) {
    if (!d->has_search_dir) {
      casadi_qr_colcomb(d->dz, d->nz_r, p->sp_r, p->pc, 1e-12, k);
    }
    for (i=0; i<p->qp->nz; ++i) {
      d->iw[i] = d->lincomb[i] && fabs(casadi_qrqp_kkt_dot(d, d->dz, i)) > 1e-12;
    }
    casadi_qrqp_expand_step(d);
    for (neg = 0; neg < 2; ++neg) {
      if (neg) {
        casadi_scal(p->qp->nz, -1., d->dz);
        casadi_scal(p->qp->nz, -1., d->dlam);
        casadi_scal(p->qp->nx, -1., d->tinfeas);
      }
      if (casadi_qrqp_pr_direction(d)) continue;
      if (casadi_qrqp_du_direction(d)) continue;
      for (i=0; i<p->qp->nz; ++i) {
        if (!d->iw[i]) continue;
        if (d->lam[i]==0.) {
          if (d->z[i] <= d->ubz[i] && (d->z[i] >= d->lbz[i] ?
              d->dz[i] < -1e-12 : d->dz[i] > 1e-12)) {
            if (!d->neverlower[i]
                && (tau_test = (d->lbz[i] - d->z[i]) / d->dz[i]) < tau
                && casadi_qrqp_enforceable(d, i, -1)) {
              tau = tau_test;
              d->r_index = i;
              d->r_sign = -1;
              best_k = k;
              best_neg = neg;
            }
          } else if (d->z[i] >= d->lbz[i] && (d->z[i] <= d->ubz[i] ?
              d->dz[i] > 1e-12 : d->dz[i] < -1e-12)) {
            if (!d->neverupper[i]
                && (tau_test = (d->ubz[i] - d->z[i]) / d->dz[i]) < tau
                && casadi_qrqp_enforceable(d, i, 1)) {
              tau = tau_test;
              d->r_index = i;
              d->r_sign = 1;
              best_k = k;
              best_neg = neg;
            }
          }
        } else if (!d->neverzero[i]) {
          if (d->lam[i] > 0 ? d->dlam[i] < -1e-12 : d->dlam[i] > 1e-12) {
            if ((tau_test = -d->lam[i] / d->dlam[i]) < tau) {
              tau = tau_test;
              d->r_index = i;
              d->r_sign = 0;
              best_k = k;
              best_neg = neg;
            }
          }
        }
      }
    }
  }
  if (d->r_index < 0) return 1;
  if (--k != best_k) {
    casadi_qr_colcomb(d->dz, d->nz_r, p->sp_r, p->pc, 1e-12, best_k);
    casadi_qrqp_expand_step(d);
    if (best_neg) tau *= -1;
  } else if (--neg != best_neg) {
    tau *= -1;
  }
  casadi_scal(p->qp->nz, tau, d->dz);
  casadi_scal(p->qp->nz, tau, d->dlam);
  casadi_scal(p->qp->nx, tau, d->tinfeas);
  return 0;
}
int casadi_qrqp_calc_step(struct casadi_qrqp_data* d) {
  const struct casadi_qrqp_prob* p = d->prob;
  d->r_index = -1;
  d->r_sign = 0;
  if (d->sing) return casadi_qrqp_singular_step(d);
  casadi_qrqp_kkt_residual(d, d->dz);
  casadi_qr_solve(d->dz, 1, 1, p->sp_v, d->nz_v, p->sp_r, d->nz_r, d->beta,
                  p->prinv, p->pc, d->w);
  casadi_qrqp_expand_step(d);
  return 0;
}
void casadi_qrqp_calc_sens(struct casadi_qrqp_data* d, casadi_int i) {
  const struct casadi_qrqp_prob* p = d->prob;
  casadi_clear(d->sens, p->qp->nz);
  if (i >= 0) {
    d->sens[i] = d->infeas[i] > 0 ? -1. : 1.;
    casadi_mv(d->qp->a, p->qp->sp_a, d->sens, d->sens + p->qp->nx, 0);
  }
}
void casadi_qrqp_calc_dependent(struct casadi_qrqp_data* d) {
  casadi_int i;
  casadi_real r;
  const struct casadi_qrqp_prob* p = d->prob;
  d->f = casadi_bilin(d->qp->h, p->qp->sp_h, d->z, d->z)/2.
       + casadi_dot(p->qp->nx, d->z, d->qp->g);
  casadi_clear(d->z+p->qp->nx, p->qp->na);
  casadi_mv(d->qp->a, p->qp->sp_a, d->z, d->z+p->qp->nx, 0);
  casadi_copy(d->qp->g, p->qp->nx, d->infeas);
  casadi_mv(d->qp->h, p->qp->sp_h, d->z, d->infeas, 0);
  casadi_mv(d->qp->a, p->qp->sp_a, d->lam+p->qp->nx, d->infeas, 1);
  for (i=0; i<p->qp->nx; ++i) {
    if (d->lam[i]==0) continue;
    r = -d->infeas[i];
    if (d->lam[i]>0) {
      if (d->neverzero[i] && !d->neverlower[i]) {
        d->lam[i] = r==0 ? p->dmin : r;
      } else {
        d->lam[i] = casadi_fmax(r, p->dmin);
      }
    } else {
      if (d->neverzero[i] && !d->neverupper[i]) {
        d->lam[i] = r==0 ? -p->dmin : r;
      } else {
        d->lam[i] = casadi_fmin(r, -p->dmin);
      }
    }
    d->infeas[i] += d->lam[i];
  }
  casadi_qrqp_pr(d);
  casadi_qrqp_du(d);
  d->epr = casadi_fmax(d->pr, (0.5 * p->constr_viol_tol / p->dual_inf_tol) * d->du);
  d->edu = casadi_fmax(d->du, (0.5 * p->dual_inf_tol / p->constr_viol_tol) * d->pr);
  casadi_qrqp_calc_sens(d, d->idu);
}
void casadi_qrqp_linesearch(struct casadi_qrqp_data* d) {
  casadi_int du_index;
  d->sign = 0;
  d->index = -1;
  d->tau = 1.;
  casadi_qrqp_primal_blocking(d);
  du_index = casadi_qrqp_dual_blocking(d);
  casadi_qrqp_take_step(d);
  if (du_index >= 0) {
    casadi_qrqp_calc_sens(d, du_index);
    casadi_qrqp_du_index(d);
  }
}
void casadi_qrqp_flip(struct casadi_qrqp_data* d) {
  const struct casadi_qrqp_prob* p = d->prob;
  if (d->index == -1 && d->r_index >= 0) {
    if (d->r_sign != 0 || casadi_qrqp_du_check(d, d->r_index)) {
      d->index = d->r_index;
      d->sign = d->r_sign;
      if (d->sign > 0) {
        d->msg = "Enforced ubz for regularity";
      } else if (d->sign < 0) {
        d->msg = "Enforced lbz for regularity";
      } else if (d->lam[d->index] > 0) {
        d->msg = "Dropped ubz for regularity";
      } else {
        d->msg = "Dropped lbz for regularity";
      }
      d->msg_ind = d->index;
    }
  }
  if (!d->sing && d->index == -1) {
    if (d->pr * p->dual_inf_tol >= p->constr_viol_tol * d->du) {
      if (d->pr >= p->constr_viol_tol) casadi_qrqp_pr_index(d);
    } else {
      if (d->du >= p->dual_inf_tol) casadi_qrqp_du_index(d);
    }
  }
  d->has_search_dir = 0;
  if (d->index >= 0) {
    if (!d->sing) d->has_search_dir = casadi_qrqp_flip_check(d);
    d->lam[d->index] = d->sign==0 ? 0 : d->sign > 0 ? p->dmin : -p->dmin;
    casadi_qrqp_calc_dependent(d);
  }
}
int casadi_qrqp_prepare(struct casadi_qrqp_data* d) {
  const struct casadi_qrqp_prob* p = d->prob;
  casadi_qrqp_calc_dependent(d);
  casadi_qrqp_flip(d);
  casadi_qrqp_factorize(d);
  if (!d->sing && d->index == -1) {
    d->status = QP_SUCCESS;
    d->msg = "Converged";
    d->msg_ind = -2;
    return 1;
  } else if (d->iter >= p->max_iter) {
    d->status = QP_MAX_ITER;
    d->msg = "Max iter";
    d->msg_ind = -2;
    return 1;
  } else if (!d->sing && d->ipr < 0 && d->idu < 0) {
    d->status = QP_SUCCESS;
    d->msg = "No primal or dual error";
    d->msg_ind = -2;
    return 1;
  } else {
    return 0;
  }
}
int casadi_qrqp_iterate(struct casadi_qrqp_data* d) {
  d->msg = 0;
  d->iter++;
  if (casadi_qrqp_calc_step(d)) {
    d->status = QP_NO_SEARCH_DIR;
    return 1;
  }
  casadi_qrqp_linesearch(d);
  return 0;
}
int casadi_qrqp_print_header(struct casadi_qrqp_data* d, char* buf, size_t buf_sz) {
#ifdef CASADI_SNPRINTF
  int flag;
  flag = CASADI_SNPRINTF(buf, buf_sz, "%5s %5s %9s %9s %5s %9s %5s %9s %5s %9s  %4s",
          "Iter", "Sing", "fk", "|pr|", "con", "|du|", "var",
          "min_R", "con", "last_tau", "Note");
  if (flag < 0) {
    d->status = QP_PRINTING_ERROR;
    return 1;
  }
#else
  if (buf_sz) buf[0] = '\0';
#endif
  return 0;
}
int casadi_qrqp_print_colcomb(struct casadi_qrqp_data* d, char* buf, size_t buf_sz, casadi_int j) {
#ifdef CASADI_SNPRINTF
  casadi_int num_size, n_print, i, k, buf_offset, val;
  size_t b;
  const struct casadi_qrqp_prob* p = d->prob;
  casadi_qr_colcomb(d->dlam, d->nz_r, p->sp_r, p->pc, 1e-12, j);
  num_size = 1;
  val = p->qp->nz-1;
  while (val) {
    val/=10;
    num_size++;
  }
  if (buf_sz<=4) return 1;
  n_print = (buf_sz-4)/num_size;
  for (b=0;b<buf_sz;++b) buf[b]=' ';
  buf_offset = 0;
  for (i=0;i<p->qp->nz;++i) {
    if (fabs(d->dlam[i]) >= 1e-12) {
      if (n_print==0) {
        buf[buf_sz-4] = '.';
        buf[buf_sz-3] = '.';
        buf[buf_sz-2] = '.';
        buf[buf_sz-1] = '\0';
        return 1;
      }
      n_print--;
      CASADI_SNPRINTF(buf+buf_offset, num_size, "%d", (int) (i));
      for (k=0;k<num_size;++k) {
        if (buf[buf_offset+k]=='\0') buf[buf_offset+k] = ' ';
      }
      buf_offset += num_size;
    }
  }
  buf[buf_sz-1] = '\0';
#else
  if (buf_sz) buf[0] = '\0';
#endif
  return 0;
}
int casadi_qrqp_print_iteration(struct casadi_qrqp_data* d, char* buf, int buf_sz) {
#ifdef CASADI_SNPRINTF
  int flag;
  flag = CASADI_SNPRINTF(buf, buf_sz,
    "%5d %5d %9.2g %9.2g %5d %9.2g %5d %9.2g %5d %9.2g  ",
    (int) (d->iter), (int) (d->sing), d->f, d->pr,
    (int) (d->ipr), d->du, (int) (d->idu),
    d->mina, (int) (d->imina), d->tau);
  if (flag < 0) {
    d->status = QP_PRINTING_ERROR;
    return 1;
  }
  buf += flag;
  buf_sz -= flag;
  if (d->msg) {
    if (d->msg_ind > -2) {
      flag = CASADI_SNPRINTF(buf, buf_sz, "%s, i=%d", d->msg, (int) (d->msg_ind));
    } else {
      flag = CASADI_SNPRINTF(buf, buf_sz, "%s", d->msg);
    }
    if (flag < 0) {
      d->status = QP_PRINTING_ERROR;
      return 1;
    }
  }
#else
  if (buf_sz) buf[0] = '\0';
#endif
  return 0;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifndef casadi_nan
  #define casadi_nan NAN
#endif

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[5] = {0, 2, 0, 0, 0};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s2[3] = {2, 0, 0};
static const casadi_int casadi_s3[8] = {2, 2, 0, 2, 3, 0, 1, 1};
static const casadi_int casadi_s4[8] = {2, 2, 0, 1, 3, 0, 0, 1};
static const casadi_int casadi_s5[2] = {0, 1};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* solver_qp:(i0[2],i1[12])->(o0[2x2],o1[2],o2[0x2],o3[0],o4[0x2],o5[]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+4, w2, w3, *w4=w+9, *w5=w+12, *w6=w+15, *w7=w+18, w8, *w9=w+22, *w10=w+24, *w11=w+27;
  /* #0: @0 = zeros(2x2) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 3, w1);
  /* #2: @2 = ones(2x1,1nz) */
  w2 = 1.;
  /* #3: {@3, NULL} = vertsplit(@2) */
  w3 = w2;
  /* #4: @4 = (@1*@3) */
  for (i=0, rr=w4, cr=w1; i<3; ++i) (*rr++)  = ((*cr++)*w3);
  /* #5: @5 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w5);
  /* #6: @6 = (@5*@3) */
  for (i=0, rr=w6, cr=w5; i<3; ++i) (*rr++)  = ((*cr++)*w3);
  /* #7: @4 = (@4-@6) */
  for (i=0, rr=w4, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #8: @6 = (2.*@4) */
  for (i=0, rr=w6, cs=w4; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #9: @3 = dot(@1, @6) */
  w3 = casadi_dot(3, w1, w6);
  /* #10: @2 = dot(@5, @6) */
  w2 = casadi_dot(3, w5, w6);
  /* #11: @3 = (@3-@2) */
  w3 -= w2;
  /* #12: @6 = input[1][2] */
  casadi_copy(arg[1] ? arg[1]+6 : 0, 3, w6);
  /* #13: @7 = (-@4) */
  for (i=0, rr=w7, cs=w4; i<3; ++i) *rr++ = (- *cs++ );
  /* #14: @7 = (@7-@4) */
  for (i=0, rr=w7, cs=w4; i<3; ++i) (*rr++) -= (*cs++);
  /* #15: @2 = dot(@6, @7) */
  w2 = casadi_dot(3, w6, w7);
  /* #16: @4 = input[1][3] */
  casadi_copy(arg[1] ? arg[1]+9 : 0, 3, w4);
  /* #17: @8 = dot(@4, @7) */
  w8 = casadi_dot(3, w4, w7);
  /* #18: @2 = (@2-@8) */
  w2 -= w8;
  /* #19: @9 = vertcat(@3, @2) */
  rr=w9;
  *rr++ = w3;
  *rr++ = w2;
  /* #20: (@0[:2] = @9) */
  for (rr=w0+0, ss=w9; rr!=w0+2; rr+=1) *rr = *ss++;
  /* #21: (@0[:4:2] = @9) */
  for (rr=w0+0, ss=w9; rr!=w0+4; rr+=2) *rr = *ss++;
  /* #22: @3 = ones(2x1,1nz) */
  w3 = 1.;
  /* #23: {NULL, @2} = vertsplit(@3) */
  w2 = w3;
  /* #24: @7 = (@6*@2) */
  for (i=0, rr=w7, cr=w6; i<3; ++i) (*rr++)  = ((*cr++)*w2);
  /* #25: @10 = (@4*@2) */
  for (i=0, rr=w10, cr=w4; i<3; ++i) (*rr++)  = ((*cr++)*w2);
  /* #26: @7 = (@7-@10) */
  for (i=0, rr=w7, cs=w10; i<3; ++i) (*rr++) -= (*cs++);
  /* #27: @10 = (-@7) */
  for (i=0, rr=w10, cs=w7; i<3; ++i) *rr++ = (- *cs++ );
  /* #28: @10 = (2.*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #29: @2 = dot(@1, @10) */
  w2 = casadi_dot(3, w1, w10);
  /* #30: @3 = dot(@5, @10) */
  w3 = casadi_dot(3, w5, w10);
  /* #31: @2 = (@2-@3) */
  w2 -= w3;
  /* #32: @7 = (2.*@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #33: @3 = dot(@6, @7) */
  w3 = casadi_dot(3, w6, w7);
  /* #34: @8 = dot(@4, @7) */
  w8 = casadi_dot(3, w4, w7);
  /* #35: @3 = (@3-@8) */
  w3 -= w8;
  /* #36: @9 = vertcat(@2, @3) */
  rr=w9;
  *rr++ = w2;
  *rr++ = w3;
  /* #37: (@0[2:4] = @9) */
  for (rr=w0+2, ss=w9; rr!=w0+4; rr+=1) *rr = *ss++;
  /* #38: (@0[1:5:2] = @9) */
  for (rr=w0+1, ss=w9; rr!=w0+5; rr+=2) *rr = *ss++;
  /* #39: @11 = @0' */
  for (i=0, rr=w11, cs=w0; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #40: output[0][0] = @11 */
  casadi_copy(w11, 4, res[0]);
  /* #41: @7 = (@5-@4) */
  for (i=0, rr=w7, cr=w5, cs=w4; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #42: @10 = (2.*@7) */
  for (i=0, rr=w10, cs=w7; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #43: @2 = dot(@1, @10) */
  w2 = casadi_dot(3, w1, w10);
  /* #44: @3 = dot(@5, @10) */
  w3 = casadi_dot(3, w5, w10);
  /* #45: @2 = (@2-@3) */
  w2 -= w3;
  /* #46: output[1][0] = @2 */
  if (res[1]) res[1][0] = w2;
  /* #47: @5 = (@5-@4) */
  for (i=0, rr=w5, cs=w4; i<3; ++i) (*rr++) -= (*cs++);
  /* #48: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) *rr++ = (- *cs++ );
  /* #49: @5 = (@5-@7) */
  for (i=0, rr=w5, cs=w7; i<3; ++i) (*rr++) -= (*cs++);
  /* #50: @2 = dot(@6, @5) */
  w2 = casadi_dot(3, w6, w5);
  /* #51: @3 = dot(@4, @5) */
  w3 = casadi_dot(3, w4, w5);
  /* #52: @2 = (@2-@3) */
  w2 -= w3;
  /* #53: output[1][1] = @2 */
  if (res[1]) res[1][1] = w2;
  return 0;
}

/* solver_qpsol:(h[2x2],g[2],a[0x2],lba[0],uba[0],lbx[2],ubx[2],x0[2],lam_x0[2],lam_a0[0],q[0x2],p[])->(x[2],cost,lam_a[0],lam_x[2]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  char buf[121];
  int flag;
  struct casadi_qp_data d_qp;
  struct casadi_qp_prob p_qp;
  struct casadi_qrqp_data d;
  struct casadi_qrqp_prob p;
  d_qp.prob = &p_qp;
  p_qp.sp_a = casadi_s0;
  p_qp.sp_h = casadi_s1;
  casadi_qp_setup(&p_qp);
  casadi_qp_init(&d_qp, &iw, &w);
  d_qp.h = arg[0];
  d_qp.g = arg[1];
  d_qp.a = arg[2];
  d_qp.lbx = arg[5];
  d_qp.ubx = arg[6];
  d_qp.lba = arg[3];
  d_qp.uba = arg[4];
  d_qp.x0 = arg[7];
  d_qp.lam_x0 = arg[8];
  d_qp.lam_a0 = arg[9];
  d_qp.f = res[1];
  d_qp.x = res[0];
  d_qp.lam_x = res[3];
  d_qp.lam_a = res[2];
  p.qp = &p_qp;
  p.sp_at = casadi_s2;
  p.sp_kkt = casadi_s1;
  p.sp_v = casadi_s3;
  p.sp_r = casadi_s4;
  p.prinv = casadi_s5;
  p.pc =  casadi_s5;
  casadi_qrqp_setup(&p);
  p.max_iter = 1000;
  p.min_lam = 0;
  p.constr_viol_tol = 1e-08;
  p.dual_inf_tol = 1e-08;
  d.prob = &p;
  d.qp = &d_qp;
  casadi_qrqp_init(&d, &iw, &w);
  /* Pass bounds on z */
  if (arg[5]) {
    casadi_copy(arg[5], 2, d.lbz);
  } else {
    casadi_fill(d.lbz, 2, -casadi_inf);
  }
  if (arg[3]) {
    casadi_copy(arg[3], 0, d.lbz+2);
  } else {
    casadi_fill(d.lbz+2, 0, -casadi_inf);
  }
  if (arg[6]) {
    casadi_copy(arg[6], 2, d.ubz);
  } else {
    casadi_fill(d.ubz, 2, casadi_inf);
  }
  if (arg[4]) {
    casadi_copy(arg[4], 0, d.ubz+2);
  } else {
    casadi_fill(d.ubz+2, 0, casadi_inf);
  }
  /* Pass initial guess */
  if (arg[7]) {
    casadi_copy(arg[7], 2, d.z);
  } else {
    casadi_clear(d.z, 2);
  }
  casadi_fill(d.z+2, 0, casadi_nan);
  if (arg[8]) {
    casadi_copy(arg[8], 2, d.lam);
  } else {
    casadi_clear(d.lam, 2);
  }
  if (arg[9]) {
    casadi_copy(arg[9], 0, d.lam+2);
  } else {
    casadi_clear(d.lam+2, 0);
  }
  /* Solve QP */
  if (casadi_qrqp_reset(&d)) return 1;
  while (1) {
    flag = casadi_qrqp_prepare(&d);
    if (d.iter % 10 == 0) {
      if (casadi_qrqp_print_header(&d, buf, sizeof(buf))) break;
      CASADI_PRINTF("%s\n", buf);
    }
    if (casadi_qrqp_print_iteration(&d, buf, sizeof(buf))) break;
    CASADI_PRINTF("%s\n", buf);
    if (flag || casadi_qrqp_iterate(&d)) break;
  }
  /* Get solution */
  if (res[1]) casadi_copy(&d.f, 1, res[1]);
  if (res[0]) casadi_copy(d.z, 2, res[0]);
  if (res[3]) casadi_copy(d.lam, 2, res[3]);
  if (res[2]) casadi_copy(d.lam+2, 0, res[2]);
  if (d.status == QP_SUCCESS) {;
    return 0;
  } else if (d.status == QP_NO_SEARCH_DIR) {
    return 4;
  } else {
    return -1000;
  }
  return 0;
}

/* constant_qp:(i0[2],i1[12])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, *w2=w+5, *w3=w+8;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[1][1] */
  casadi_copy(arg[1] ? arg[1]+3 : 0, 3, w1);
  /* #2: @2 = input[1][3] */
  casadi_copy(arg[1] ? arg[1]+9 : 0, 3, w2);
  /* #3: @3 = (@1-@2) */
  for (i=0, rr=w3, cr=w1, cs=w2; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #4: @3 = @3' */
  /* #5: @1 = (@1-@2) */
  for (i=0, rr=w1, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #6: @0 = mac(@3,@1,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #7: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* solver:(x0[2],p[12],lbx[2],ubx[2],lbg[0],ubg[0],lam_x0[2],lam_g0[0])->(x[2],f,g[0],lam_x[2],lam_g[0],lam_p[12]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+6;
  const casadi_real **arg1=arg+8;
  casadi_real *w0=w+34, *w1=w+36, *w2=w+48, *w3=w+52, *w7=w+54, *w8=w+56, *w9=w+58, *w13=w+60, w14, *w15=w+63, w16;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 2, w0);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 12, w1);
  /* #2: {@2, @3, NULL, NULL, NULL, NULL} = solver_qp(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=w2;
  res1[1]=w3;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #3: @4 = 0x2 */
  /* #4: @5 = 0x1 */
  /* #5: @6 = 0x1 */
  /* #6: @7 = input[2][0] */
  casadi_copy(arg[2], 2, w7);
  /* #7: @8 = input[3][0] */
  casadi_copy(arg[3], 2, w8);
  /* #8: @9 = input[6][0] */
  casadi_copy(arg[6], 2, w9);
  /* #9: @10 = 0x1 */
  /* #10: @11 = 0x2 */
  /* #11: @12 = 0x0 */
  /* #12: {@13, @14, NULL, @15} = solver_qpsol(@2, @3, @4, @5, @6, @7, @8, @0, @9, @10, @11, @12) */
  arg1[0]=w2;
  arg1[1]=w3;
  arg1[2]=0;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=w7;
  arg1[6]=w8;
  arg1[7]=w0;
  arg1[8]=w9;
  arg1[9]=0;
  arg1[10]=0;
  arg1[11]=0;
  res1[0]=w13;
  res1[1]=(&w14);
  res1[2]=0;
  res1[3]=w15;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: output[0][0] = @13 */
  casadi_copy(w13, 2, res[0]);
  /* #14: @16 = constant_qp(@0, @1) */
  arg1[0]=w0;
  arg1[1]=w1;
  res1[0]=(&w16);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #15: @16 = (@16+@14) */
  w16 += w14;
  /* #16: output[1][0] = @16 */
  if (res[1]) res[1][0] = w16;
  /* #17: output[3][0] = @15 */
  casadi_copy(w15, 2, res[3]);
  /* #18: @1 = nan(12x1) */
  casadi_fill(w1, 12, casadi_nan);
  /* #19: output[5][0] = @1 */
  casadi_copy(w1, 12, res[5]);
  return 0;
}

/* Collition_Fcn:(i0[2],i1[2],i2[12])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+3, *cs;
  casadi_real *w0=w+66, *w1=w+68, *w2=w+71, *w3=w+74, *w4=w+77, *w5=w+80, *w6=w+92, *w7=w+94, *w10=w+96, *w12=w+98;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 2, w0);
  /* #1: @1 = input[2][0] */
  casadi_copy(arg[2], 3, w1);
  /* #2: @2 = input[2][1] */
  casadi_copy(arg[2] ? arg[2]+3 : 0, 3, w2);
  /* #3: @3 = input[2][2] */
  casadi_copy(arg[2] ? arg[2]+6 : 0, 3, w3);
  /* #4: @4 = input[2][3] */
  casadi_copy(arg[2] ? arg[2]+9 : 0, 3, w4);
  /* #5: @5 = vertcat(@1, @2, @3, @4) */
  rr=w5;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #6: @6 = zeros(2x1) */
  casadi_clear(w6, 2);
  /* #7: @7 = ones(2x1) */
  casadi_fill(w7, 2, 1.);
  /* #8: @8 = 0x1 */
  /* #9: @9 = 0x1 */
  /* #10: @10 = input[1][0] */
  casadi_copy(arg[1], 2, w10);
  /* #11: @11 = 0x1 */
  /* #12: {@12, NULL, NULL, NULL, NULL, NULL} = solver(@0, @5, @6, @7, @8, @9, @10, @11) */
  arg1[0]=w0;
  arg1[1]=w5;
  arg1[2]=w6;
  arg1[3]=w7;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=w10;
  arg1[7]=0;
  res1[0]=w12;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #13: output[0][0] = @12 */
  casadi_copy(w12, 2, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Collition_Fcn(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Collition_Fcn_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Collition_Fcn_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Collition_Fcn_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Collition_Fcn_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Collition_Fcn_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Collition_Fcn_incref(void) {
}

CASADI_SYMBOL_EXPORT void Collition_Fcn_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Collition_Fcn_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Collition_Fcn_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Collition_Fcn_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Collition_Fcn_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Collition_Fcn_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Collition_Fcn_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Collition_Fcn_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Collition_Fcn_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 23;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 10;
  if (sz_w) *sz_w = 100;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_Collition_Fcn(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[118];
  casadi_int iw[10];
  const casadi_real* arg[23] = {0};
  casadi_real* res[15] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Collition_Fcn\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Collition_Fcn\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s6, w+18);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+2, casadi_s6, w+18);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+4, casadi_s7, w+18);
  --resc;
  res[0] = w+16;
  Collition_Fcn_incref();
  mem = Collition_Fcn_checkout();
  i = Collition_Fcn(arg, res, iw, w+18, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Collition_Fcn\" failed.");
  Collition_Fcn_release(mem);
  Collition_Fcn_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s6, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[14];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_Collition_Fcn(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "Collition_Fcn")==0) {
    mex_Collition_Fcn(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'Collition_Fcn'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
